### PR TITLE
Add JSDoc (mainly for typings)

### PR DESCRIPTION
**Pull request by DataM0del**
for autocomplete I guess but yes lol

### CODE REVIEW

**Comment by DataM0del** [comment]
Probably shouldn't be manually adding types, those should be auto-generated by a script.
Will develop a tool that will use the types provided from the definition of `fields` via the `ut` (`Object.create` wrapper because POV we need IE 11 support) calls and grab the types from the proto field lists.

**Comment by DataM0del** [comment]
I am almost done with making the auto-generator for the typings, it gets them from the `fields` property on any protobuf object in Miniblox. Just need to fix JSDoc typings being [Object Object] instead of number or string.

**Comment by DataM0del** [comment]
> I am almost done with making the auto-generator for the typings, it gets them from the `fields` property on any protobuf object in Miniblox. Just need to fix JSDoc typings being [Object Object] instead of number or string.

Fixed the JSDoc typings.

**Comment by DataM0del** [comment]
I also need to make it automatic.

**Comment by 40ea57d3ee3c07bf1c102b466e1c3091** [comment]
rewrite kills this

**Comment by DataM0del** [comment]
Yay! Conflicts...
Will resolve.

**Pull request closed without merging**
