### PR TITLE
feat: add autocomplete to /queue and /play commands

### PR DESCRIPTION
**Pull request by DataM0del**
Hardcoding gamemodes / server types :fire:
Also need to test in a second

### CODE REVIEW

**Comment by DataM0del** [comment]
doesn't work, fixing...

**Comment by DataM0del** [comment]
Fixed in e483ac5

**Comment by 7GrandDadPGN** [comment]
Added

**Comment by DataM0del** [comment]
image
and not pushed

**Comment by DataM0del** [comment]
Also, that is NOT how anyone should be merging PRs, unless your name is cURL...

**Pull request closed without merging**
