### PR TITLE
chore: format with prettier

### PR DESCRIPTION
**Pull request by DataM0del**
Default config but useTabs is set to true.
Should probably include the .prettierrc but no one is going to use it so...
Yes, it made the script longer, but this script needs to be split into a few files in order to not be fat.

### CODE REVIEW

**Comment by joeengo** [comment]
shut the fuck up

**Comment by DataM0del** [comment]
> shut the fuck up

not a maintainer, opinion immediately discarded.

**Comment by joeengo** [comment]
> > shut the fuck up
> 
> not a maintainer, opinion immediately discarded.

no name no body wants your stupid chore commits that literally do not contribute in any meaningful way

**Comment by DataM0del** [comment]
> > > shut the fuck up
> > 
> > 
> > not a maintainer, opinion immediately discarded.
> 
> no name no body wants your stupid chore commits that literally do not contribute in any meaningful way

image

**Comment by joeengo** [comment]
image

**Comment by DataM0del** [comment]
> image

eww imgflip watermark just save the image from the canvas.

**Comment by 7GrandDadPGN** [comment]
firefox_QWIdeWbwo8
firefox_KVB7QdV7c9
mm no

**Pull request closed without merging**
